version: '3.8'
services:
  inventory-service:
    build: ./inventory_service
    ports:
      - "5000:5000"

  order-service:
    build: ./order_service
    ports:
      - "6000:6000"
    depends_on:
      - inventory-service
#hello
