name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build docker image
      run: |
        docker build . --file Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/inventory-service:latest

    - name: Login to YC Registry
      uses: docker/login-action@v1 
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YC_KEYS }}
    
    - name: Push tag to YC Registry
      run: |
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/inventory_service:latest 
